# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 小人驿站
subtitle: '模拟电路工程师'
description: '怀出世之心，行入世之事。'
keywords:
author: 市井一俗人
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://shenguosai.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source  # 用来存放内容，如markdown写的博文
public_dir: public  # 用来存放生成的静态博客文件
tag_dir: tags  # 标签文件夹
archive_dir: archives  # 归档文件夹
category_dir: categories  # 分类文件夹
code_dir: downloads/code  # Include code 文件夹
i18n_dir: :lang  # 国际化 (i18n) 文件夹
skip_render:  # 跳过指定文件的渲染，您可以使用 glob 来配置路径

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## s: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape
#theme: hexo-theme-matery
#theme: hexo-theme-next
#theme: next

encrypt: #hexo-blog-encrypt
  enable: true
  abstract: 有东西被加密了, 请输入密码查看.
  message: 您好, 这里需要密码.
  tags:
  - {name: Privacy, password: 20110204}
  - {name: Work, password: MC.12345}
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试.
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
# repo: https://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@github.com/shenguosai/shenguosai.github.io.git
  repo: git@github.com:shenguosai/shenguosai.github.io.git
  branch: master

symbols_count_time:
  symbols: true             # 文章字数统计
  time: true                # 文章阅读时长
  total_symbols: true       # 站点总字数统计
  total_time: true          # 站点总阅读时长
  exclude_codeblock: false  # 排除代码字数统计

math:
  engine: 'mathjax'
  mathjax:
    src: custom_mathjax_source
    config:
      # MathJax config
